# Generated by Django 4.2.5 on 2023-09-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('importance', models.CharField(max_length=50)),
            ],
        ),
    ]
